app/models.py
#!/usr/bin/env python -*- coding: utf-8 -*-
from datetime import datetime
from hashlib import md5
from time import time
from flask import current_app
from app import db


class MicroEmpresa(db.Model):

	__tablename__ = 'microempresa'
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(200), index=True, unique=True)
	location = db.Column(db.String(200), index=True)
	goal = db.Column(db.String(200), index=True, unique=True)
	description = db.Column(db.String(800), index=True)
	timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
	apoio = db.relationship(
        'Apoiar',
        foreign_keys='Apoiar.microempresa_id',
        backref='microempresa', lazy='dynamic')

	def like_microempresa(self, apoiar):
		if not self.has_liked_microempresa(apoiar):
			like = Apoiar(microempresa_id=self.id, apoiar_id=apoiar.id)
			db.session.add(like)

	def has_liked_microempresa(self, apoiar):
		return Apoiar.query.filter(
			Apoiar.microempresa_id == self.id,
			Apoiar.apoiar_id == apoiar.id).count() > 0

	def __repr__(self):
		return '{}'.format(self.title)


class Apoiar(db.Model):

	id = db.Column(db.Integer, primary_key=True)
	apoiar = db.Column(db.String(200), index=True)
	timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)

	microempresa_id = db.Column(db.Integer, db.ForeignKey('microempresa.id'))
	apoiar_id = db.Column(db.Integer, db.ForeignKey('apoiar.id'))

	def __repr__(self):
		return '{}'.format(self.apoiar)

app/__init__.py
#!/usr/bin/env python# -*- coding: utf-8 -*-
import logging
from logging.handlers import RotatingFileHandler
import os
from flask import Flask, request, current_app
import threading
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_moment import Moment
from flask_babel import Babel, lazy_gettext as _l
from flask_bootstrap import Bootstrap
from config import Config

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))
migrate = Migrate()
moment = Moment()
babel = Babel()
bootstrap = Bootstrap()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db, render_as_batch=True)
    bootstrap.init_app(app)
    moment.init_app(app)
    babel.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

    if not app.debug and not app.testing:
        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/app.log',
                                               maxBytes=10240, backupCount=10)
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s '
                '[in %(pathname)s:%(lineno)d]'))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Plataforma startup')

    return app

@babel.localeselector
def get_locale():
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
#!/usr/bin/env python# -*- coding: utf-8 -*-
import sys
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g, \
    jsonify, current_app, Response
from flask_babel import _, get_locale
from app import db
from app.main.form import MicroEmpresaForm
from app.models import MicroEmpresa, Apoiar
from app.main import bp

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    microempresa = MicroEmpresa.query.order_by(MicroEmpresa.timestamp.desc()).all()
    return render_template('index.html', title=(_('Página Inicial')), microempresa=microempresa)

@bp.route('/explore', methods=['GET', 'POST'])
def explore():
    microempresa = MicroEmpresa.query.order_by(MicroEmpresa.timestamp.desc()).all()
    return render_template('explore.html', title=(_('Explorar')), microempresa=microempresa)

@bp.route('/register_microempresa', methods=['GET', 'POST'])
def register_microempresa():
    form = MicroEmpresaForm()
    if form.validate_on_submit():
        microempresa = MicroEmpresa(title=form.title.data, description=form.description.data,
        goal=form.goal.data, location=form.location.data)
        db.session.add(microempresa)
        db.session.commit()
        flash(_('Cadastro realizado com sucesso!'))
    return render_template('register_microempresa.html', title=(_('Cadastrar Ideia')), form=form)

@bp.route('/edit_microempresa/<int:id>', methods=['GET', 'POST'])
def edit_microempresa(id):
    microempresa = MicroEmpresa.query.get_or_404(id)
    form = MicroEmpresaForm()
    if form.validate_on_submit():
        microempresa.title = form.title.data
        microempresa.description = form.description.data
        microempresa.goal = form.goal.data
        microempresa.location = form.location.data
        db.session.add(microempresa)
        db.session.commit()
        flash(_('As alterações foram salvas!'))
    form.title.data = microempresa.title
    form.description.data = microempresa.description
    form.goal.data = microempresa.goal
    form.location.data = microempresa.location
    return render_template('edit_microempresa.html', title=(_('Editar Ideia')),
                           form=form, microempresa=microempresa)

@bp.route("/deletar_microempresa/<int:id>")
def deletar_microempresa(id):
    microempresa = MicroEmpresa.query.filter_by(id=id).first()
    db.session.delete(microempresa)
    db.session.commit()
    flash(_('Apagado com sucesso!'))
    return redirect(url_for("main.index"))

@bp.route('/microempresa_profile/<title>', methods=['GET', 'POST'])
def microempresa_profile(title):
    microempresa = MicroEmpresa.query.filter_by(title=title).first_or_404()
    return render_template('microempresa_profile.html', title=(_('Perfil da Ideia')),
        microempresa=microempresa)

@bp.route('/about', methods=['GET', 'POST'])
def about():
    return render_template('about.html', title=(_('Sobre')))

app/templates/_microempresa.html
<table>
  <div class="card">
  <tr valign="top">
    <td>
      <h4><a class="card-title" href="{{ url_for('main.microempresa_profile', title=microempresa.title) }}">
        {{ microempresa.title }}</a></h4>
      <p class="card-text">Descrição: {{ microempresa.description }} <br>
        Meta Financeira: {{ microempresa.goal }}<br>
        Localização: {{ microempresa.location }}</p>
    </td>
  </tr>
  </div>
</table>

app/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h1>Sobre</h1>
    <p>Plataforma web de colaboração financeira destinada a ajudar pequenas e
      micro empresas a buscarem possíveis investidores para a sua ideia de negócio. <br><br>
      A ideia de desenvolver Connect ACT é pensada na problemática em oferecer melhores
      experiências por meio de tecnologias que conectem de forma eficiente e simplificada
      pequenos e micro empreendedores a investidores <br><br>
      O projeto deu seu início ao desenvolvimento no Hackaton da PotiLivre no ano de 2020.
      O tema do Hackaton é sobre buscar soluções para pequenas e micro empresas usando
      Software Livre.</p>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

<!DOCTYPE html>
<html>
{% block html_attribs %} lang="pt-br"{% endblock %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block styles %}{{super()}}
    <link rel="stylesheet" href="{{url_for('static', filename='css/mystyle.css')}}">
    {% endblock %}

    <title>{% block title %}{% if title %}{{ title }} - Connect ACT
    {% else %}Bem-vindo à Connect ACT{% endif %}{% endblock %}</title>
</head>
<body>
    {% block navbar %}
    <nav class="navbar navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="{{'/'}}">
          <img class="navbar-brand" src="../static/image/logo_connectACT.png" alt="Logo Connect ACT"></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a class="link_text" href="{{ url_for('main.explore') }}">Encontrar diversas ideia de Negócio</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('main.register_microempresa') }}">Registrar ideia de Negócio</a></li>
            <li><a href="{{ url_for('main.about') }}">Sobre</a></li>
          </ul>
        </div>

    </div>
    </nav>
    {% endblock %}

    {% block content %}
    <div class="container">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <br><div class="alert alert-info text-center" role="alert">{{ message }}</div><br>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {# application content needs to be provided in the app_content block #}
      {% block app_content %}{% endblock %}
    {% endblock content %}


</body>
</html>

app/templates/edit_microempresa.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<h1 class="text-center">Editar ideia de Negócio</h1>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
      {{ wtf.quick_form(form) }}
  </div>
  <div class="col-md-3"></div>
</div>
{% endblock %}

app/templates/explore.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h1>Explorar</h1>
    
      <div class="row">
        {% for microempresa in microempresa %}
        <div class="col-sm">
          {% include '_microempresa.html' %}<br>
        </div>
        {% endfor%}

    

      
    

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="container apresentacao">
    <h1>Connect ACT</h1>
    <p>Plataforma de colaboração financeira destinada a ajudar pequenas e micro
       empresas a investirem em ideias de negócio.</p><hr>

    <h2>Encontre diversas ideias de negócios cadastradas por micro e pequenas empresas</h2>
    

    {% for microempresa in microempresa %}
      {% include '_microempresa.html' %}<br>
    {% endfor%}
  </div>

{% endblock %}

app/templates/microempresa_profile.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid profile">
  <div class="row">
    <div class="col-md-12">
      <h1>{% if microempresa.title %}{{ microempresa.title }}{% endif %}</h1>
        <p>{% if microempresa.description %}Descrição: {{ microempresa.description }}{% endif %}<br>
        {% if microempresa.goal %}Meta Financeira: {{microempresa.goal}}{% endif %}<br>
        {% if microempresa.location %}Localização: {{microempresa.location}}{% endif %}</p>
        <button type="button" name="button">Apoiar ideia financeiramente</button><br><br>
        <p><a href="{{ url_for('main.edit_microempresa', id=microempresa.id) }}">
          {{_('Editar Ideia')}}</a> |
          <a href="{{ url_for('main.deletar_microempresa', id=microempresa.id) }}">
          {{_('Apagar Ideia')}}</a></p>
    </div>
  </div>
</div>
{% endblock %}

app/templates/register_microempresa.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
    <h1 class="text-center">Registrar novo Negocio</h1>
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
          {{ wtf.quick_form(form) }}
      </div>
      <div class="col-md-3"></div>
    </div>
{% endblock %}